'use client';

import { Download, Info } from "lucide-react";
import { DesignVariation, MachineConfig, SpecSummary } from "@/lib/types";
import { svgToPngBlob, downloadBlob } from "@/lib/utils";
import { useState } from "react";

interface ExportCardProps {
  variation: DesignVariation;
  editedImageUrl: string | null;
  config: MachineConfig;
}

function buildSpecSummary(variation: DesignVariation, config: MachineConfig): SpecSummary {
  const { validation } = variation;
  return {
    patternRepeatWidth: validation.patternRepeatSize.width,
    patternRepeatHeight: validation.patternRepeatSize.height,
    estimatedPPI: validation.estimatedPPI,
    shaftCount: validation.shaftUsed,
    recommendedSpeed: validation.recommendedSpeed,
    colorCount: validation.colorsUsed,
    yarnType: config.yarnType,
    fabricWeightGSM: config.fabricWeightGSM,
  };
}

export default function ExportCard({ variation, editedImageUrl, config }: ExportCardProps) {
  const [isExporting, setIsExporting] = useState(false);
  const spec = buildSpecSummary(variation, config);
  const currentImageUrl = editedImageUrl || variation.imageUrl;

  const handleExport = async () => {
    setIsExporting(true);
    try {
      // Convert SVG/image to canvas, add spec overlay, download
      const canvas = document.createElement("canvas");
      canvas.width = 1200;
      canvas.height = 1400;
      const ctx = canvas.getContext("2d");
      if (!ctx) throw new Error("Canvas not available");

      // Draw fabric image
      const img = new Image();
      img.crossOrigin = "anonymous";
      await new Promise<void>((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = reject;
        img.src = currentImageUrl;
      });
      ctx.drawImage(img, 0, 0, 1200, 1000);

      // Spec card background
      ctx.fillStyle = "#0F0E17";
      ctx.fillRect(0, 1000, 1200, 400);

      // Gold accent line
      ctx.fillStyle = "#F5A623";
      ctx.fillRect(0, 1000, 1200, 3);

      // LoomAI branding
      ctx.fillStyle = "#F5A623";
      ctx.font = "bold 36px Arial, sans-serif";
      ctx.fillText("LoomAI", 60, 1060);

      ctx.fillStyle = "rgba(255,255,255,0.5)";
      ctx.font = "20px Arial, sans-serif";
      ctx.fillText("AI-Powered Textile Design — Toyota Rapier Dobby Loom", 60, 1090);

      // Spec items
      const specItems = [
        { label: "Pattern Repeat", value: `${spec.patternRepeatWidth} × ${spec.patternRepeatHeight} cm` },
        { label: "Est. Picks/inch", value: `${spec.estimatedPPI} PPI` },
        { label: "Shafts Used", value: `${spec.shaftCount} / ${config.dobbyShafts}` },
        { label: "Rec. Speed", value: `${spec.recommendedSpeed} PPM` },
        { label: "Colors (Weft)", value: `${spec.colorCount} channels` },
        { label: "Fabric Weight", value: `${spec.fabricWeightGSM} GSM` },
        { label: "Yarn", value: spec.yarnType },
        { label: "Reed Width", value: `${config.reedWidth} cm` },
      ];

      const colWidth = 280;
      const startX = 60;
      const startY = 1140;
      specItems.forEach((item, i) => {
        const col = i % 4;
        const row = Math.floor(i / 4);
        const x = startX + col * colWidth;
        const y = startY + row * 80;

        ctx.fillStyle = "rgba(255,255,255,0.4)";
        ctx.font = "16px Arial, sans-serif";
        ctx.fillText(item.label, x, y);

        ctx.fillStyle = "#FFFFFF";
        ctx.font = "bold 22px Arial, sans-serif";
        ctx.fillText(item.value, x, y + 28);
      });

      // Watermark in bottom right
      ctx.fillStyle = "rgba(255,255,255,0.2)";
      ctx.font = "14px Arial, sans-serif";
      ctx.textAlign = "right";
      ctx.fillText("Generated by LoomAI • loomai.in", 1140, 1380);

      canvas.toBlob((blob) => {
        if (blob) {
          downloadBlob(blob, `loomai-design-${Date.now()}.png`);
        }
      }, "image/png");
    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setIsExporting(false);
    }
  };

  const specItems = [
    { label: "Pattern Repeat", value: `${spec.patternRepeatWidth} × ${spec.patternRepeatHeight} cm`, hint: "Repeat tile size" },
    { label: "Est. Picks/inch", value: `${spec.estimatedPPI} PPI`, hint: "Weft density estimate" },
    { label: "Shafts Used", value: `${spec.shaftCount} / ${config.dobbyShafts}`, hint: "Of available shafts" },
    { label: "Rec. Speed", value: `${spec.recommendedSpeed} PPM`, hint: "Picks per minute" },
    { label: "Weft Colors", value: `${spec.colorCount}`, hint: "Of ${config.weftChannels} channels" },
    { label: "Fabric Weight", value: `${spec.fabricWeightGSM} GSM`, hint: config.yarnType },
  ];

  return (
    <div className="space-y-5 animate-slide-up">
      <h3 className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
        Export Design
      </h3>

      {/* Design preview with spec overlay */}
      <div className="rounded-2xl overflow-hidden relative" style={{ border: "1px solid var(--border-subtle)" }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={currentImageUrl}
          alt="Final design"
          className="w-full"
          style={{ maxHeight: 280, objectFit: "cover" }}
        />
        {/* Gradient overlay */}
        <div
          className="absolute bottom-0 left-0 right-0 p-3"
          style={{ background: "linear-gradient(to top, rgba(15,14,23,0.98), transparent)" }}
        >
          <p className="text-xs font-semibold" style={{ color: "var(--primary)" }}>LoomAI Design</p>
          <p className="text-xs" style={{ color: "var(--text-muted)" }}>
            {config.yarnType} · {config.reedWidth}cm reed · {config.dobbyShafts}-shaft
          </p>
        </div>
      </div>

      {/* Spec Summary Card */}
      <div
        className="rounded-2xl p-4"
        style={{ background: "var(--bg-card)", border: "1px solid var(--border-subtle)" }}
      >
        <div className="flex items-center gap-2 mb-3">
          <Info size={14} style={{ color: "var(--primary)" }} />
          <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "var(--primary)" }}>
            Production Spec Summary
          </p>
        </div>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
          {specItems.map((item) => (
            <div key={item.label} className="rounded-xl p-3" style={{ background: "rgba(255,255,255,0.04)" }}>
              <p className="text-xs mb-1" style={{ color: "var(--text-muted)" }}>{item.label}</p>
              <p className="text-base font-bold" style={{ color: "var(--text-primary)" }}>{item.value}</p>
              <p className="text-xs mt-0.5" style={{ color: "var(--text-muted)" }}>{item.hint}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Color swatches */}
      {variation.colors.length > 0 && (
        <div>
          <p className="text-xs mb-2" style={{ color: "var(--text-muted)" }}>Weft color palette used:</p>
          <div className="flex gap-2">
            {variation.colors.map((color, i) => (
              <div key={i} className="flex flex-col items-center gap-1">
                <div
                  className="w-8 h-8 rounded-lg shadow-lg"
                  style={{ background: color, border: "1px solid rgba(255,255,255,0.1)" }}
                />
                <span className="text-xs font-mono" style={{ color: "var(--text-muted)", fontSize: "9px" }}>
                  {color}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Export button */}
      <button
        type="button"
        onClick={handleExport}
        disabled={isExporting}
        className="w-full py-3.5 rounded-2xl font-semibold flex items-center justify-center gap-3 transition-all"
        style={{
          background: isExporting ? "rgba(245,166,35,0.3)" : "var(--primary)",
          color: isExporting ? "var(--text-muted)" : "#000",
          cursor: isExporting ? "wait" : "pointer",
        }}
      >
        {isExporting ? (
          <>
            <div className="w-5 h-5 rounded-full border-2 border-transparent animate-spin"
              style={{ borderTopColor: "#000" }} />
            Preparing export…
          </>
        ) : (
          <>
            <Download size={18} />
            Download High-Res PNG
          </>
        )}
      </button>
      <p className="text-xs text-center" style={{ color: "var(--text-muted)" }}>
        Downloads a 1200×1400px PNG with fabric image + production spec card
      </p>
    </div>
  );
}
